### ISSUE TITLE
Add Blocks/Items and Fix Bugs

### ISSUE THREAD

**Issue by BlawoHD** [BlueLightJapan/BlueLight#113]
# Blocks

- [x] add EnderChest (#52)

# Items

- [x] add Enchanted Golden Apple
- [x] add Splash Potions

# Bugs

- [ ] Fix SubChunk (#17)
- [ ] Add/Fix Enchanting (#53)
- [x] Fix Player eat (#78)
- [x] Fix Furnace (#107 / #121)
- [x] Fix Crafting for Win10 (#109)
- [x] Fix Items drop of Inventory (#115)
- [x] Fix Effect on golden apple

**Comment by kametan0730MC** [comment]
We can use SplashPotions ,if you set bluelight.properties true.

**Comment by BlawoHD** [comment]
@kametan0730MC I wait for enderchest

**Comment by BlawoHD** [comment]
@nightmare3832 
https://github.com/BlueLightJapan/BlueLight/commit/2f9dda61c94e4ce8efe513b922cf2fb3f3daa693
1.0.0 Blocks has add?

**Comment by kametan0730MC** [comment]
I will implement it soon

**Comment by kametan0730MC** [comment]
What is "Fix bluelight.properties"?

**Comment by BlawoHD** [comment]
@kametan0730MC Could I be a member?

**Comment by kametan0730MC** [comment]
Yes!!

**Comment by kametan0730MC** [comment]
I invited you.

**Comment by BlawoHD** [comment]
@kametan0730MC Thx :)

**Comment by kametan0730MC** [comment]
Thank you too

**Comment by BlawoHD** [comment]
@kametan0730MC Can you fix SubChunk times?
